# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  DATABASE_PRIMARY_RW_URL: "postgresql://USERNAME:PASSWORD@localhost:5432/"
  DATABASE_CACHE_RW_URL: "postgresql://USERNAME:PASSWORD@localhost:5432/"
  DATABASE_QUEUE_RW_URL: "postgresql://USERNAME:PASSWORD@localhost:5432/"
  DATABASE_CABLE_RW_URL: "postgresql://USERNAME:PASSWORD@localhost:5432/"
  DATABASE_USERNAME: "ckretz"
  DATABASE_PASSWORD: "secret"
  DATABASE_SUPER_USERNAME: "postgres"
  DATABASE_SUPER_PASSWORD: "secret"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  rubocop:
    cmds:
      - echo "rubocop ..."
      - bundle exec rubocop

  dagger_publish:
    cmds:
      - dagger call publish --source=. -v

  rswag:
    env:
      DOMAIN_NAME: "localhost:3000"
    cmds:
      - bundle exec rake rswag:specs:swaggerize
  rspec:
    env:
      COVERAGE: 1
      RAILS_ENV: test
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "deterministickeyaaaaaaaaaaaaaaaa"
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "keyderivationsaltbbbbbbbbbbbbbbb"
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "primarykeycccccccddddddddddddddd"
    cmds:
      - bundle exec rspec --profile --format d;

  simplecov:
    cmds:
      - open coverage/index.html

  console:
    dotenv:
      - .bin/env
    cmds:
      - bundle exec rails console

  tailwind:
    cmds:
      - bundle exec rails tailwindcss:watch

  solid_queue:
    dotenv:
      - .bin/env
    env:
      RLS_DISABLE: "true"
      PGGSSENCMODE: "disable"
    cmds:
      - bundle exec rails solid_queue:start

  psql_user_create:
    cmds:
      - cmd: |
          psql -U $(whoami) postgres -c "
            create user ckretz with password 'secret';
          "
        ignore_error: true

  psql_user_permissions:
    cmds:
      - |
        setup () {
          echo "setting up database: ${2} for user: ${1}";
          psql -U $(whoami) ${2} -c "
            GRANT all privileges on DATABASE ${2} to ${1};
            GRANT ALL privileges on all TABLES in SCHEMA public to ${1};
            GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO ${1};
            GRANT ALL ON SCHEMA public TO ${1};
            GRANT USAGE ON SCHEMA public TO ${1};
            GRANT CONNECT ON DATABASE  ${2} to ${1};
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${1};
          "
        }
        setup "ckretz" "ckretz_primary_development"
        setup "ckretz" "ckretz_cache_development"
        setup "ckretz" "ckretz_queue_development"
        setup "ckretz" "ckretz_cable_development"

