default: &default
  database: cache
  size_estimate_samples: 1000
  store_options:
    max_age: <%= 7.days.to_i %>
    max_size: <%= 128.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
