default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: warning # Minimum log levels, in increasing order:#   debug5, debug4, debug3, debug2, debug1,#   log, notice, warning, error, fatal, and panic# Defaults to warning.
  username: <%=  ENV.fetch("DB_SUPER_USERNAME", ENV.fetch("DB_USERNAME", "ckretz") ) %>
  password: <%=  ENV.fetch("DB_SUPER_PASSWORD",  ENV.fetch("DB_PASSWORD", "secret") ) %>


development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: ckretz_primary_development
    migrations_paths: db/migrate_primary
  cache:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    database: ckretz_cache_development
    migrations_paths: db/migrate_cache
  queue:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RW_URL'] %>
    database: ckretz_queue_development
    migrations_paths: db/migrate_queue
  cable:
    <<: *default
    url: <%= ENV['DATABASE_CABLE_RW_URL'] %>
    database: ckretz_cable_development
    migrations_paths: db/migrate_cable

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    host: localhost
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: ckretz_primary_test
    migrations_paths: db/migrate_primary
  cache:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    database: ckretz_cache_test
    migrations_paths: db/migrate_cache
  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_RW_URL"] %>
    database: ckretz_queue_test
    migrations_paths: db/migrate_queue
    host: localhost
  cable:
    <<: *default
    url: <%= ENV['DATABASE_CABLE_RW_URL'] %>
    database: ckretz_cable_test
    migrations_paths: db/migrate_cable
    host: localhost

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_PRIMARY_RW_URL"] %>
    database: 'ckretz_primary_production'
    migrations_paths: db/migrate_primary
  cache:
    <<: *default
    database: 'ckretz_cache_production'
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    migrations_paths: db/migrate_cache
  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_RW_URL"] %>
    database: 'ckretz_queue_production'
    migrations_paths: db/migrate_queue
  cable:
    <<: *default
    url: <%= ENV['DATABASE_CABLE_RW_URL'] %>
    database: 'ckretz_cable_production'
    migrations_paths: db/migrate_cable
