require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :solid_cache_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

  config.active_job.queue_name_prefix = "ckretz_development"

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  config.generators.apply_rubocop_autocorrect_after_generate!

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    user_name: ENV.fetch("MAILTRAP_USERNAME", ""),
    password: ENV.fetch("MAILTRAP_PASSWORD", ""),
    address: ENV.fetch("MAILTRAP_ADDRESS", ""),
    host: ENV.fetch("MAILTRAP_HOST", ""),
    port: ENV.fetch("MAILTRAP_PORT", ""),
    authentication: :login
  }

  # propshaft
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

   config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "info")

  if ENV.fetch("LOGGER", "standard") == "fluentd"
     config.lograge.enabled = true
     config.lograge.formatter = Lograge::Formatters::Json.new
     config.lograge.logger = Fluent::Logger::LevelFluentLogger.new(ENV.fetch("FLUENTD_HOST", "ckretz_development"))
     config.lograge.custom_options = lambda do |event|
       { current_user_id: event.payload.dig(:custom_payload, :current_user_id) }
     end
     config.lograge.logger.formatter = proc do |severity, datetime, progname, message|
       {
         span_id: OpenTelemetry::Trace.current_span.context.hex_span_id,
         trace_id: OpenTelemetry::Trace.current_span.context.hex_trace_id,
         operation: OpenTelemetry::Trace.current_span.try(:name),
         severity: severity,
         progname: progname,
         messages: if message.include?('{"method":')
                     message
                   elsif message.is_a?(Hash)
                     message.to_json
                   else
                     { body: message }.to_json
                   end
       }
     end
    config.logger = config.lograge.logger

  elsif  ENV.fetch("LOGGER", "standard") == "open_telemetry"
    logger = ::Logger.new(STDOUT)
    logger.formatter = proc do |severity, time, progname, msg|
      span_id = OpenTelemetry::Trace.current_span.context.hex_span_id
      trace_id = OpenTelemetry::Trace.current_span.context.hex_trace_id
      if defined? OpenTelemetry::Trace.current_span.name
        operation = OpenTelemetry::Trace.current_span.name
      else
        operation = "undefined"
      end

      "#{time}, #{severity}: #{msg} - trace_id=#{trace_id} - span_id=#{span_id} - operation=#{operation}\n"
    end
    config.logger = logger
  else
    config.logger = ::Logger.new(STDOUT)
  end
  config.hosts << ENV.fetch("API_DOMAIN_NAME", "localhost:3000")

  config.after_initialize do
    Prosopite.rails_logger = true
  end
end
